### ISSUE TITLE
Image link doesn't works in render

### ISSUE THREAD

**Issue by ldez** [bwklein/asciidoc-image-helper#14] opened 2016-05-06 11:59 UTC
You have remove my change that add image folder in image link (https://github.com/bwklein/asciidoc-image-helper/commit/8a9463850df75ad47b1c16f1c3337c3719021b92) but without that the link image doesn't works.

Without image folder:
![capture du 2016-05-06 13-56-42](https://cloud.githubusercontent.com/assets/5674651/15072377/a237355e-1392-11e6-830f-45cb4af2f5e9.png)

With image folder:
![capture du 2016-05-06 13-58-10](https://cloud.githubusercontent.com/assets/5674651/15072378/a250251e-1392-11e6-9d3b-ed9fe09712ac.png)

**Comment by bwklein** [comment] 2016-05-06 16:40
Yes, this is by design to not hard code the path into the image macros and use the :imagesdir: attribute in the document to tell the processor where to look for image files.  See changes to the README for a note on this feature.

**Comment by ldez** [comment] 2016-05-06 17:00
Sorry, I haven't read the documentation :wink:

Have the possibility to activate/deactivate the `:imagesdir:` support can be useful, see #15.

**Comment by bwklein** [comment] 2016-05-06 17:01
Yes, I like that improvement and have merged it in to master.

**Comment by ldez** [comment] 2016-05-06 17:01
Too speed, I finish to write my comment and PR is merge :smile:

**Closed by bwklein** 2016-05-06 17:01 UTC

**Comment by bwklein** [comment] 2016-05-06 17:03
:)
